"""DS-160 extended sections: family, travel, work/education, additional, security, SSN."""

# OCR extract keys → canonical profile keys
DS160_EXTRACT_MAP: dict[str, str] = {
    # Father
    "father_surname": "family.father_surname",
    "father_given_names": "family.father_given_names",
    "father_date_of_birth": "family.father_date_of_birth",
    "father_birth_city": "family.father_birth_city",
    "father_birth_state": "family.father_birth_state",
    "father_birth_country": "family.father_birth_country",
    "father_is_living": "family.father_is_living",
    "father_death_year": "family.father_death_year",
    "father_address": "family.father_address_line1",
    "father_city": "family.father_city",
    "father_state": "family.father_state",
    "father_postal_code": "family.father_postal_code",
    "father_country": "family.father_country",
    "father_name": "family.father_name",
    # Mother
    "mother_surname": "family.mother_surname",
    "mother_given_names": "family.mother_given_names",
    "mother_date_of_birth": "family.mother_date_of_birth",
    "mother_birth_city": "family.mother_birth_city",
    "mother_birth_state": "family.mother_birth_state",
    "mother_birth_country": "family.mother_birth_country",
    "mother_is_living": "family.mother_is_living",
    "mother_death_year": "family.mother_death_year",
    "mother_address": "family.mother_address_line1",
    "mother_city": "family.mother_city",
    "mother_state": "family.mother_state",
    "mother_postal_code": "family.mother_postal_code",
    "mother_country": "family.mother_country",
    "mother_name": "family.mother_name",
    # Spouse
    "spouse_surname": "family.spouse_surname",
    "spouse_given_names": "family.spouse_given_names",
    "spouse_date_of_birth": "family.spouse_date_of_birth",
    "spouse_birth_city": "family.spouse_birth_city",
    "spouse_birth_state": "family.spouse_birth_state",
    "spouse_birth_country": "family.spouse_birth_country",
    "spouse_address": "family.spouse_address_line1",
    "spouse_occupation": "family.spouse_occupation",
    "spouse_occupation_other": "family.spouse_occupation_other",
    "spouse_marriage_date": "family.spouse_marriage_date",
    "spouse_marriage_city": "family.spouse_marriage_city",
    "spouse_marriage_state": "family.spouse_marriage_state",
    "spouse_marriage_country": "family.spouse_marriage_country",
    "spouse_immigrating_with_you": "family.spouse_immigrating_with_you",
    "spouse_name": "family.spouse_name",
    # Previous spouses & children
    "previous_spouses_used": "family.previous_spouses_used",
    "previous_spouses_history": "family.previous_spouses_history",
    "children_used": "family.children_used",
    "children_count": "family.children_count",
    "children_history": "family.children_history",
    # U.S. travel
    "us_visited_used": "travel.us_visited_used",
    "us_visit_history": "travel.us_visit_history",
    "us_visa_issued_used": "travel.us_visa_issued_used",
    "us_visa_history": "travel.us_visa_history",
    "us_refused_used": "travel.us_refused_used",
    "us_refused_history": "travel.us_refused_history",
    # Current employment
    "primary_occupation": "employment.primary_occupation",
    "occupation_other_specify": "employment.occupation_other_specify",
    "present_employer": "employment.present_employer",
    "employer_address": "employment.employer_address_line1",
    "employer_city": "employment.employer_city",
    "employer_state": "employment.employer_state",
    "employer_postal_code": "employment.employer_postal_code",
    "employer_country": "employment.employer_country",
    "other_occupation_used": "employment.other_occupation_used",
    "other_occupation_detail": "employment.other_occupation_detail",
    "prior_jobs_10_years_used": "employment.prior_jobs_10_years_used",
    "prior_jobs_history": "employment.prior_jobs_history",
    # Education (secondary+)
    "middle_school_name": "education.middle_school_name",
    "middle_school_address": "education.middle_school_address",
    "middle_school_period": "education.middle_school_period",
    "high_school_name": "education.high_school_name",
    "high_school_address": "education.high_school_address",
    "high_school_period": "education.high_school_period",
    "college_name": "education.college_name",
    "college_address": "education.college_address",
    "college_major": "education.college_major",
    "college_period": "education.college_period",
    # Additional
    "military_served_used": "additional.military_served_used",
    "military_country": "additional.military_country",
    "military_branch": "additional.military_branch",
    "military_rank": "additional.military_rank",
    "military_specialty": "additional.military_specialty",
    "military_service_from": "additional.military_service_from",
    "military_service_to": "additional.military_service_to",
    "other_languages_used": "additional.other_languages_used",
    "other_languages_detail": "additional.other_languages_detail",
    "travel_5_years_used": "additional.travel_5_years_used",
    "travel_5_years_detail": "additional.travel_5_years_detail",
    # SSN
    "ssn_applied_before": "ssn.applied_before",
    "ssn_applied_detail": "ssn.applied_detail",
    "ssn_want_card": "ssn.want_card_issued",
    "ssn_authorize_disclosure": "ssn.authorize_disclosure",
}

# Security & background — Yes/No per DS-160 question
SECURITY_KEYS: list[str] = [
    "security.health_tuberculosis",
    "security.health_vaccinations",
    "security.health_mental_disorder",
    "security.health_drug_abuse",
    "security.crime_arrested",
    "security.crime_controlled_substances",
    "security.crime_spouse_drug_trafficking_benefit",
    "security.crime_prostitution",
    "security.crime_money_laundering",
    "security.crime_human_trafficking",
    "security.crime_aid_human_trafficker",
    "security.crime_family_human_trafficking_benefit",
    "security.illegal_activity_us",
    "security.terrorist_activities",
    "security.terrorist_financial_support",
    "security.terrorist_organization_member",
    "security.terrorist_family_support",
    "security.genocide",
    "security.torture",
    "security.extrajudicial_killings",
    "security.child_soldiers",
    "security.religious_freedom_violations",
    "security.totalitarian_party",
    "security.farc_support",
    "security.property_expropriation",
    "security.family_property_expropriation",
    "security.forced_abortion_sterilization",
    "security.chemical_weapons_info",
    "security.family_chemical_weapons_info",
    "security.immigration_fraud",
    "security.deported",
    "security.child_custody_withheld",
    "security.aid_child_custody_withheld",
    "security.illegal_voting",
    "security.renounce_citizenship_tax",
    "security.f_visa_public_school_unpaid",
    "security.uncertified_labor",
    "security.foreign_medical_no_exam",
    "security.healthcare_worker_no_cert",
    "security.permanently_ineligible_citizenship",
    "security.evade_military_service",
    "security.polygamy",
    "security.j_visa_residence_requirement",
    "security.frivolous_asylum",
    "security.public_charge",
]

for _key in SECURITY_KEYS:
    short = _key.split(".", 1)[1]
    DS160_EXTRACT_MAP[short] = _key
    DS160_EXTRACT_MAP[f"security_{short}"] = _key

# Legacy DS-160 review sections — không còn hiển thị trên UI (workflow dùng doc records).
# Giữ định nghĩa để export Word / FIELD_LABELS tham chiếu nếu cần.
_DS160_PROFILE_SECTIONS_LEGACY: dict[str, list[str]] = {
    "family_father": [
        "family.father_surname",
        "family.father_given_names",
        "family.father_name",
        "family.father_date_of_birth",
        "family.father_birth_city",
        "family.father_birth_state",
        "family.father_birth_country",
        "family.father_is_living",
        "family.father_death_year",
        "family.father_address_line1",
        "family.father_city",
        "family.father_state",
        "family.father_postal_code",
        "family.father_country",
    ],
    "family_mother": [
        "family.mother_surname",
        "family.mother_given_names",
        "family.mother_name",
        "family.mother_date_of_birth",
        "family.mother_birth_city",
        "family.mother_birth_state",
        "family.mother_birth_country",
        "family.mother_is_living",
        "family.mother_death_year",
        "family.mother_address_line1",
        "family.mother_city",
        "family.mother_state",
        "family.mother_postal_code",
        "family.mother_country",
    ],
    "family_spouse": [
        "family.spouse_surname",
        "family.spouse_given_names",
        "family.spouse_name",
        "family.spouse_date_of_birth",
        "family.spouse_birth_city",
        "family.spouse_birth_state",
        "family.spouse_birth_country",
        "family.spouse_address_line1",
        "family.spouse_occupation",
        "family.spouse_occupation_other",
        "family.spouse_marriage_date",
        "family.spouse_marriage_city",
        "family.spouse_marriage_state",
        "family.spouse_marriage_country",
        "family.spouse_immigrating_with_you",
    ],
    "family_previous_spouses": [
        "family.previous_spouses_used",
        "family.previous_spouses_history",
    ],
    "family_children": [
        "family.children_used",
        "family.children_count",
        "family.children_history",
    ],
    "travel_us": [
        "travel.us_visited_used",
        "travel.us_visit_history",
        "travel.us_visa_issued_used",
        "travel.us_visa_history",
        "travel.us_refused_used",
        "travel.us_refused_history",
    ],
    "employment_current": [
        "employment.primary_occupation",
        "employment.occupation_other_specify",
        "employment.present_employer",
        "employment.employer_name",
        "employment.employer_address_line1",
        "employment.employer_city",
        "employment.employer_state",
        "employment.employer_postal_code",
        "employment.employer_country",
        "employment.other_occupation_used",
        "employment.other_occupation_detail",
        "employment.prior_jobs_10_years_used",
        "employment.prior_jobs_history",
        "employment.job_title",
        "employment.salary",
        "employment.start_date",
    ],
    "education_schools": [
        "education.middle_school_name",
        "education.middle_school_address",
        "education.middle_school_period",
        "education.high_school_name",
        "education.high_school_address",
        "education.high_school_period",
        "education.college_name",
        "education.college_address",
        "education.college_major",
        "education.college_period",
        "education.school_name",
        "education.degree",
        "education.gpa",
        "education.graduation_date",
        "education.program_name",
        "education.program_start_date",
        "education.program_end_date",
    ],
    "additional_info": [
        "additional.military_served_used",
        "additional.military_country",
        "additional.military_branch",
        "additional.military_rank",
        "additional.military_specialty",
        "additional.military_service_from",
        "additional.military_service_to",
        "additional.other_languages_used",
        "additional.other_languages_detail",
        "additional.travel_5_years_used",
        "additional.travel_5_years_detail",
    ],
    "security_background": SECURITY_KEYS,
    "ssn": [
        "ssn.applied_before",
        "ssn.applied_detail",
        "ssn.want_card_issued",
        "ssn.authorize_disclosure",
    ],
}

DS160_FIELD_LABELS_VI: dict[str, str] = {
    "family.father_surname": "Cha — Họ",
    "family.father_given_names": "Cha — Tên",
    "family.father_name": "Cha — Họ tên (gộp)",
    "family.father_date_of_birth": "Cha — Ngày sinh",
    "family.father_birth_city": "Cha — TP nơi sinh",
    "family.father_birth_state": "Cha — Tỉnh/Bang nơi sinh",
    "family.father_birth_country": "Cha — Quốc gia nơi sinh",
    "family.father_is_living": "Cha — Còn sống? (Yes/No)",
    "family.father_death_year": "Cha — Năm mất",
    "family.father_address_line1": "Cha — Địa chỉ hiện tại",
    "family.father_city": "Cha — Thành phố",
    "family.father_state": "Cha — Tỉnh/Bang",
    "family.father_postal_code": "Cha — Mã bưu điện",
    "family.father_country": "Cha — Quốc gia",
    "family.mother_surname": "Mẹ — Họ",
    "family.mother_given_names": "Mẹ — Tên",
    "family.mother_name": "Mẹ — Họ tên (gộp)",
    "family.mother_date_of_birth": "Mẹ — Ngày sinh",
    "family.mother_birth_city": "Mẹ — TP nơi sinh",
    "family.mother_birth_state": "Mẹ — Tỉnh/Bang nơi sinh",
    "family.mother_birth_country": "Mẹ — Quốc gia nơi sinh",
    "family.mother_is_living": "Mẹ — Còn sống? (Yes/No)",
    "family.mother_death_year": "Mẹ — Năm mất",
    "family.mother_address_line1": "Mẹ — Địa chỉ hiện tại",
    "family.mother_city": "Mẹ — Thành phố",
    "family.mother_state": "Mẹ — Tỉnh/Bang",
    "family.mother_postal_code": "Mẹ — Mã bưu điện",
    "family.mother_country": "Mẹ — Quốc gia",
    "family.spouse_surname": "Vợ/chồng — Họ",
    "family.spouse_given_names": "Vợ/chồng — Tên",
    "family.spouse_name": "Vợ/chồng — Họ tên (gộp)",
    "family.spouse_date_of_birth": "Vợ/chồng — Ngày sinh",
    "family.spouse_birth_city": "Vợ/chồng — TP nơi sinh",
    "family.spouse_birth_state": "Vợ/chồng — Tỉnh/Bang nơi sinh",
    "family.spouse_birth_country": "Vợ/chồng — Quốc gia nơi sinh",
    "family.spouse_address_line1": "Vợ/chồng — Địa chỉ hiện tại",
    "family.spouse_occupation": "Vợ/chồng — Nghề nghiệp",
    "family.spouse_occupation_other": "Vợ/chồng — Ngành nghề (ghi rõ)",
    "family.spouse_marriage_date": "Ngày kết hôn",
    "family.spouse_marriage_city": "Kết hôn tại — Thành phố",
    "family.spouse_marriage_state": "Kết hôn tại — Tỉnh/Bang",
    "family.spouse_marriage_country": "Kết hôn tại — Quốc gia",
    "family.spouse_immigrating_with_you": "Vợ/chồng nhập cư cùng? (Yes/No)",
    "family.previous_spouses_used": "Có vợ/chồng trước? (Yes/No)",
    "family.previous_spouses_history": "Chi tiết vợ/chồng cũ (ly hôn, ngày cưới…)",
    "family.children_used": "Có con? (Yes/No)",
    "family.children_count": "Số con / ghi chú",
    "family.children_history": "Chi tiết từng con (tên, DOB, địa chỉ, nhập cư…)",
    "travel.us_visited_used": "Đã từng đến Mỹ? (Yes/No)",
    "travel.us_visit_history": "Chi tiết lần đến Mỹ",
    "travel.us_visa_issued_used": "Đã được cấp visa Mỹ? (Yes/No)",
    "travel.us_visa_history": "Chi tiết visa Mỹ",
    "travel.us_refused_used": "Bị từ chối visa/nhập cảnh? (Yes/No)",
    "travel.us_refused_history": "Chi tiết từ chối visa/nhập cảnh",
    "employment.primary_occupation": "Nghề nghiệp chính",
    "employment.occupation_other_specify": "Ngành nghề (ghi rõ)",
    "employment.present_employer": "Công ty / trường hiện tại",
    "employment.employer_address_line1": "Địa chỉ công ty",
    "employment.employer_city": "Công ty — Thành phố",
    "employment.employer_state": "Công ty — Tỉnh/Bang",
    "employment.employer_postal_code": "Công ty — Mã bưu điện",
    "employment.employer_country": "Công ty — Quốc gia",
    "employment.other_occupation_used": "Có việc làm khác? (Yes/No)",
    "employment.other_occupation_detail": "Chi tiết việc làm khác",
    "employment.prior_jobs_10_years_used": "Làm việc khác 10 năm qua? (Yes/No)",
    "employment.prior_jobs_history": "Lịch sử việc làm 10 năm (công ty, chức danh, ngày…)",
    "education.middle_school_name": "THCS — Tên trường",
    "education.middle_school_address": "THCS — Địa chỉ",
    "education.middle_school_period": "THCS — Thời gian học",
    "education.high_school_name": "THPT — Tên trường",
    "education.high_school_address": "THPT — Địa chỉ",
    "education.high_school_period": "THPT — Thời gian học",
    "education.college_name": "CĐ/ĐH — Tên trường",
    "education.college_address": "CĐ/ĐH — Địa chỉ",
    "education.college_major": "CĐ/ĐH — Ngành học",
    "education.college_period": "CĐ/ĐH — Thời gian học",
    "additional.military_served_used": "Đã phục vụ quân đội? (Yes/No)",
    "additional.military_country": "NVQS — Quốc gia",
    "additional.military_branch": "NVQS — Khu/Chiến khu",
    "additional.military_rank": "NVQS — Cấp bậc / vị trí",
    "additional.military_specialty": "NVQS — Chuyên ngành",
    "additional.military_service_from": "NVQS — Từ ngày",
    "additional.military_service_to": "NVQS — Đến ngày",
    "additional.other_languages_used": "Ngôn ngữ khác ngoài tiếng Việt? (Yes/No)",
    "additional.other_languages_detail": "Chi tiết ngôn ngữ khác",
    "additional.travel_5_years_used": "Du lịch nước khác 5 năm? (Yes/No)",
    "additional.travel_5_years_detail": "Chi tiết du lịch 5 năm",
    "ssn.applied_before": "Đã xin SSN? (Yes/No)",
    "ssn.applied_detail": "Chi tiết đơn SSN",
    "ssn.want_card_issued": "Muốn cấp thẻ SSN? (Yes/No)",
    "ssn.authorize_disclosure": "Cho phép tiết lộ thông tin SSN? (Yes/No)",
}

SECURITY_LABELS_VI: dict[str, str] = {
    "security.health_tuberculosis": "Bệnh lao / bệnh lây lan công cộng?",
    "security.health_vaccinations": "Có giấy tờ tiêm chủng theo luật Mỹ?",
    "security.health_mental_disorder": "Rối loạn tâm thần/thể chất đe dọa an toàn?",
    "security.health_drug_abuse": "Đang/đã nghiện ma túy?",
    "security.crime_arrested": "Bị bắt/kết án (kể cả được ân xá)?",
    "security.crime_controlled_substances": "Vi phạm luật chất cấm?",
    "security.crime_spouse_drug_trafficking_benefit": "Vợ/chồng/con buôn ma túy — hưởng lợi 5 năm?",
    "security.crime_prostitution": "Mại dâm / kinh doanh bất hợp pháp 10 năm?",
    "security.crime_money_laundering": "Rửa tiền?",
    "security.crime_human_trafficking": "Buôn người?",
    "security.crime_aid_human_trafficker": "Giúp buôn người (Tổng thống xác định)?",
    "security.crime_family_human_trafficking_benefit": "Gia đình buôn người — hưởng lợi 5 năm?",
    "security.illegal_activity_us": "Gián điệp/phá hoại/vi phạm xuất khẩu tại Mỹ?",
    "security.terrorist_activities": "Hoạt động khủng bố?",
    "security.terrorist_financial_support": "Hỗ trợ tài chính khủng bố?",
    "security.terrorist_organization_member": "Thành viên tổ chức khủng bố?",
    "security.terrorist_family_support": "Gia đình hỗ trợ khủng bố 5 năm?",
    "security.genocide": "Diệt chủng?",
    "security.torture": "Tra tấn?",
    "security.extrajudicial_killings": "Giết người phi pháp/chính trị/bạo lực?",
    "security.child_soldiers": "Tuyển/dùng binh lính trẻ em?",
    "security.religious_freedom_violations": "Vi phạm tự do tôn giáo (quan chức)?",
    "security.totalitarian_party": "Đảng cộng sản/độc tài?",
    "security.farc_support": "Hỗ trợ FARC/ELN/AUC Colombia?",
    "security.property_expropriation": "Chiếm đoạt tài sản người Mỹ?",
    "security.family_property_expropriation": "Gia đình chiếm đoạt tài sản người Mỹ?",
    "security.forced_abortion_sterilization": "Ép phá thai/triệt sản?",
    "security.chemical_weapons_info": "Tiết lộ thông tin Vũ khí hóa học?",
    "security.family_chemical_weapons_info": "Gia đình tiết lộ thông tin VKHH?",
    "security.immigration_fraud": "Gian lận visa/nhập cư?",
    "security.deported": "Bị trục xuất khỏi nước khác?",
    "security.child_custody_withheld": "Giữ con công dân Mỹ trái quyền nuôi?",
    "security.aid_child_custody_withheld": "Giúp giữ con công dân Mỹ trái quyền?",
    "security.illegal_voting": "Bầu cử trái phép tại Mỹ?",
    "security.renounce_citizenship_tax": "Từ bỏ quốc tịch Mỹ tránh thuế?",
    "security.f_visa_public_school_unpaid": "Học trường công F visa không hoàn tiền?",
    "security.uncertified_labor": "Lao động chưa chứng nhận Bộ Lao động?",
    "security.foreign_medical_no_exam": "Bác sĩ nước ngoài chưa qua thi?",
    "security.healthcare_worker_no_cert": "Y tá/điều dưỡng chưa chứng nhận?",
    "security.permanently_ineligible_citizenship": "Vĩnh viễn không đủ điều kiện quốc tịch Mỹ?",
    "security.evade_military_service": "Rời Mỹ tránh nghĩa vụ quân sự?",
    "security.polygamy": "Đến Mỹ thực hành đa thê?",
    "security.j_visa_residence_requirement": "J visa chưa đủ 2 năm cư trú nước ngoài?",
    "security.frivolous_asylum": "Đơn tị nạn vô căn cứ?",
    "security.public_charge": "Có thể trở thành gánh nặng công?",
}

DS160_FIELD_LABELS_VI.update(SECURITY_LABELS_VI)

# Long-text profile keys (review UI textarea)
DS160_LONG_TEXT_KEYS: frozenset[str] = frozenset(
    {
        "family.previous_spouses_history",
        "family.children_history",
        "travel.us_visit_history",
        "travel.us_visa_history",
        "travel.us_refused_history",
        "employment.prior_jobs_history",
        "employment.other_occupation_detail",
        "ssn.applied_detail",
        "additional.other_languages_detail",
        "additional.travel_5_years_detail",
    }
)

DS160_FORM_MAPPINGS: dict[str, str] = {
    "Father Surname": "family.father_surname",
    "Father Given Names": "family.father_given_names",
    "Mother Surname": "family.mother_surname",
    "Mother Given Names": "family.mother_given_names",
    "Mother Date of Birth": "family.mother_date_of_birth",
    "Mother Birth City": "family.mother_birth_city",
    "Mother Birth Country": "family.mother_birth_country",
    "Mother Living": "family.mother_is_living",
    "Mother Address": "family.mother_address_line1",
    "Mother City": "family.mother_city",
    "Mother Postal Code": "family.mother_postal_code",
    "Mother Country": "family.mother_country",
    "Previous Spouses": "family.previous_spouses_used",
    "Previous Spouses Detail": "family.previous_spouses_history",
    "Children": "family.children_used",
    "Children Count": "family.children_count",
    "Children Detail": "family.children_history",
    "US Visited": "travel.us_visited_used",
    "US Visa Issued": "travel.us_visa_issued_used",
    "US Visa Refused": "travel.us_refused_used",
    "Primary Occupation": "employment.primary_occupation",
    "Present Employer": "employment.present_employer",
    "Employer Address": "employment.employer_address_line1",
    "Prior Jobs 10 Years": "employment.prior_jobs_10_years_used",
    "Prior Jobs Detail": "employment.prior_jobs_history",
    "Middle School": "education.middle_school_name",
    "High School": "education.high_school_name",
    "College": "education.college_name",
    "College Major": "education.college_major",
    "Military Service": "additional.military_served_used",
    "Travel 5 Years": "additional.travel_5_years_used",
    "Travel 5 Years Detail": "additional.travel_5_years_detail",
    "SSN Applied": "ssn.applied_before",
    "SSN Want Card": "ssn.want_card_issued",
    "SSN Authorize": "ssn.authorize_disclosure",
}

DS160_OCR_HINT = """
For DS-160 FAMILY: father/mother/spouse surnames, given names, DOB, birth city/state/country,
living (YES/NO), death year, current address; previous_spouses_used/history; children_used, count, history.

TRAVEL: us_visited_used, us_visa_issued_used, us_refused_used and detail histories if YES.

WORK/EDUCATION: primary_occupation, present_employer, employer address; prior_jobs_10_years_used, prior_jobs_history;
middle/high/college school name, address, period, college_major.

ADDITIONAL: military_served_used and military fields; other_languages_used; travel_5_years_used/detail.

SECURITY: each security.* field as YES or NO.

SSN: ssn_applied_before, ssn_want_card, ssn_authorize_disclosure.
"""
