"""Canonical field keys and document-type → profile mapping."""

from app.services.document_registry import STANDARD_DOCUMENT_TYPES
from app.services.ds160_extended import (
    DS160_EXTRACT_MAP,
    DS160_FIELD_LABELS_VI,
    DS160_FORM_MAPPINGS,
    DS160_OCR_HINT,
)

DOCUMENT_TYPES = [
    *STANDARD_DOCUMENT_TYPES,
    "visa",
    "i20",
    "i94",
    "diploma_transcript",
    "financial",
    "employment_letter",
    "application_form",
    "address_document",
    "ds260_customer_form",
    "photo",
    "other",
]

# Source priority (lower index = higher priority)
SOURCE_PRIORITY = [
    "passport",
    "judicial_certificate",
    "birth_certificate",
    "birth_certificate_child",
    "marriage_certificate",
    "divorce",
    "death_certificate",
    "military_discharge",
    "visa",
    "i94",
    "i20",
    "diploma_transcript",
    "financial",
    "employment_letter",
    "application_form",
    "address_document",
    "ds260_customer_form",
    "other",
]

# DS-160 Address & contact (shared across address-related document types)
CONTACT_ADDRESS_MAP: dict[str, str] = {
    "current_address": "contact.address_line1",
    "address_line1": "contact.address_line1",
    "street_address": "contact.address_line1",
    "address": "contact.address_line1",
    "residential_address": "contact.address_line1",
    "mailing_address": "contact.address_line1",
    "contact_city": "contact.city",
    "address_city": "contact.city",
    "city": "contact.city",
    "contact_state": "contact.state",
    "address_state": "contact.state",
    "state": "contact.state",
    "province": "contact.state",
    "state_province": "contact.state",
    "postal_code": "contact.postal_code",
    "zip_code": "contact.postal_code",
    "postal_zone": "contact.postal_code",
    "zip": "contact.postal_code",
    "contact_country": "contact.country",
    "address_country": "contact.country",
    "country": "contact.country",
    "address_from_date": "contact.address_from_date",
    "from_date": "contact.address_from_date",
    "residence_from": "contact.address_from_date",
    "lived_since": "contact.address_from_date",
    "other_addresses_since_16": "contact.other_addresses_used",
    "other_addresses_used": "contact.other_addresses_used",
    "lived_elsewhere_since_16": "contact.other_addresses_used",
    "prior_addresses": "contact.other_addresses_history",
    "other_addresses_history": "contact.other_addresses_history",
    "address_history": "contact.other_addresses_history",
    "previous_addresses": "contact.other_addresses_history",
    # Phone — DS-160 Contact Information
    "primary_phone": "contact.phone_primary",
    "primary_phone_number": "contact.phone_primary",
    "phone_primary": "contact.phone_primary",
    "secondary_phone": "contact.phone_secondary",
    "secondary_phone_number": "contact.phone_secondary",
    "phone_secondary": "contact.phone_secondary",
    "work_phone": "contact.phone_work",
    "work_phone_number": "contact.phone_work",
    "phone_work": "contact.phone_work",
    "other_phones_used": "contact.other_phones_used",
    "other_telephones_used": "contact.other_phones_used",
    "other_phone_used_last_5_years": "contact.other_phones_used",
    "other_phones_history": "contact.other_phones_history",
    "other_telephone_numbers": "contact.other_phones_history",
    "other_phones_detail": "contact.other_phones_history",
    "phone": "contact.phone_primary",
    "mobile": "contact.phone_primary",
    "telephone": "contact.phone_primary",
    # Email
    "email": "contact.email",
    "email_address": "contact.email",
    "primary_email": "contact.email",
    "other_emails_used": "contact.other_emails_used",
    "other_email_used": "contact.other_emails_used",
    "other_email_used_last_5_years": "contact.other_emails_used",
    "other_emails_history": "contact.other_emails_history",
    "other_email_addresses": "contact.other_emails_history",
    "other_emails_detail": "contact.other_emails_history",
}

# DS-160 Social Media
SOCIAL_MEDIA_MAP: dict[str, str] = {
    "social_media_platform": "social.platform",
    "social_platform": "social.platform",
    "social_media_provider": "social.platform",
    "platform_provider": "social.platform",
    "social_media_identifier": "social.identifier",
    "social_identifier": "social.identifier",
    "social_profile_url": "social.identifier",
    "profile_url": "social.identifier",
    "social_media_url": "social.identifier",
    "facebook_url": "social.identifier",
    "other_social_media_used": "social.other_used",
    "other_social_used": "social.other_used",
    "other_social_media_5_years": "social.other_used",
    "other_social_used_last_5_years": "social.other_used",
    "other_social_history": "social.other_history",
    "other_social_media_history": "social.other_history",
    "other_social_media_detail": "social.other_history",
    "other_social_detail": "social.other_history",
}

CONTACT_AND_SOCIAL_MAP: dict[str, str] = {**CONTACT_ADDRESS_MAP, **SOCIAL_MEDIA_MAP}

# DS-260 / generic forms classified as "other"
OTHER_FORM_MAP: dict[str, str] = {
    "passport_id": "passport.number",
    "passport_number": "passport.number",
    "passport_country": "passport.issuing_country",
    "passport_issue_date": "passport.issue_date",
    "passport_expiration_date": "passport.expiry_date",
    "passport_expiry_date": "passport.expiry_date",
    "sex": "identity.gender",
    "zip_code": "contact.postal_code",
    "postal_zone": "contact.postal_code",
}

# Extracted field keys per document type → canonical profile keys
FIELD_MAP: dict[str, dict[str, str]] = {
    "passport": {
        # DS-160 Section A — Personal
        "family_name": "identity.family_name",
        "surname": "identity.family_name",
        "last_name": "identity.family_name",
        "given_names": "identity.given_names",
        "given_name": "identity.given_names",
        "first_name": "identity.given_names",
        "middle_name": "identity.middle_name",
        "full_name": "identity.full_name",
        "name": "identity.full_name",
        "full_name_native": "identity.full_name_native",
        "name_native_language": "identity.full_name_native",
        "native_full_name": "identity.full_name_native",
        "other_name_used": "identity.other_name_used",
        "has_other_names": "identity.other_name_used",
        "other_names": "identity.other_names",
        "other_name": "identity.other_names",
        "alias": "identity.other_names",
        "gender": "identity.gender",
        "sex": "identity.gender",
        "marital_status": "identity.marital_status",
        "current_marital_status": "identity.marital_status",
        "date_of_birth": "identity.date_of_birth",
        "dob": "identity.date_of_birth",
        "birth_date": "identity.date_of_birth",
        "birth_city": "identity.birth_city",
        "city_of_birth": "identity.birth_city",
        "birth_state": "identity.birth_state",
        "state_of_birth": "identity.birth_state",
        "province_of_birth": "identity.birth_state",
        "birth_country": "identity.birth_country",
        "country_of_birth": "identity.birth_country",
        "place_of_birth": "identity.place_of_birth",
        "nationality": "identity.nationality",
        "country_of_origin": "identity.nationality",
        "country_of_nationality": "identity.nationality",
        # Passport / travel document
        "passport_number": "passport.number",
        "passport_id": "passport.number",
        "document_number": "passport.number",
        "passport_no": "passport.number",
        "passport_issue_date": "passport.issue_date",
        "issuance_date": "passport.issue_date",
        "issue_date": "passport.issue_date",
        "date_of_issue": "passport.issue_date",
        "passport_expiry_date": "passport.expiry_date",
        "expiry_date": "passport.expiry_date",
        "expiration_date": "passport.expiry_date",
        "date_of_expiry": "passport.expiry_date",
        "passport_issuing_country": "passport.issuing_country",
        "issuing_country": "passport.issuing_country",
        "country_of_issue": "passport.issuing_country",
        "authority": "passport.issuing_country",
        "country_code": "passport.issuing_country",
        "passport_type": "other.document_type",
        "document_type": "other.document_type",
        "type": "other.document_type",
        "id_card_number": "other.document_number",
        "national_id": "other.document_number",
        "cmnd": "other.document_number",
        "cccd": "other.document_number",
        "place_of_issue": "passport.issuing_country",
        "issuing_authority": "passport.issuing_country",
        "passport_place_of_issue": "passport.issuing_country",
    },
    "visa": {
        "visa_type": "immigration.visa_type",
        "visa_number": "immigration.visa_number",
        "visa_issue_date": "immigration.visa_issue_date",
        "visa_expiry_date": "immigration.visa_expiry_date",
        "full_name": "identity.full_name",
        "nationality": "identity.nationality",
    },
    "i20": {
        "sevis_id": "immigration.sevis_id",
        "school_name": "education.school_name",
        "program_name": "education.program_name",
        "program_start_date": "education.program_start_date",
        "program_end_date": "education.program_end_date",
        "full_name": "identity.full_name",
        "date_of_birth": "identity.date_of_birth",
    },
    "i94": {
        "admission_number": "immigration.i94_number",
        "class_of_admission": "immigration.class_of_admission",
        "admit_until_date": "immigration.admit_until_date",
        "full_name": "identity.full_name",
    },
    "birth_certificate": {
        "full_name": "identity.full_name",
        "name": "identity.full_name",
        "surname": "identity.family_name",
        "family_name": "identity.family_name",
        "given_name": "identity.given_names",
        "given_names": "identity.given_names",
        "date_of_birth": "identity.date_of_birth",
        "dob": "identity.date_of_birth",
        "place_of_birth": "identity.place_of_birth",
        "birth_place": "identity.place_of_birth",
        "gender": "identity.gender",
        "sex": "identity.gender",
        "nationality": "identity.nationality",
        "father_name": "family.father_name",
        "mother_name": "family.mother_name",
        "father_full_name": "family.father_name",
        "mother_full_name": "family.mother_name",
        **DS160_EXTRACT_MAP,
    },
    "marriage_certificate": {
        "spouse_name": "family.spouse_name",
        "husband_name": "family.spouse_name",
        "husband_full_name": "family.spouse_name",
        "wife_name": "family.spouse_name",
        "wife_full_name": "family.spouse_name",
        "marriage_date": "family.spouse_marriage_date",
        "marriage_place": "family.spouse_marriage_city",
        "document_number": "other.document_number",
        **DS160_EXTRACT_MAP,
    },
    "judicial_certificate": {
        "full_name": "identity.full_name",
        "name": "identity.full_name",
        "date_of_birth": "identity.date_of_birth",
        "dob": "identity.date_of_birth",
        "nationality": "identity.nationality",
        "father_name": "family.father_name",
        "mother_name": "family.mother_name",
        "father_full_name": "family.father_name",
        "mother_full_name": "family.mother_name",
        "document_number": "other.document_number",
        "document_type": "other.document_type",
        "issue_date": "other.document_issue_date",
        **DS160_EXTRACT_MAP,
    },
    "divorce": {
        "full_name": "identity.full_name",
        "name": "identity.full_name",
        "husband_full_name": "identity.full_name",
        "wife_full_name": "family.previous_spouses_history",
        "spouse_name": "family.previous_spouses_history",
        "plaintiff_name": "family.previous_spouses_history",
        "defendant_name": "identity.full_name",
        "marriage_date": "family.previous_spouses_history",
        "divorce_date": "family.previous_spouses_history",
        "document_number": "other.document_number",
        "document_type": "other.document_type",
        **DS160_EXTRACT_MAP,
    },
    "death_certificate": {
        "deceased_full_name": "family.father_name",
        "full_name": "family.father_name",
        "date_of_death": "family.father_death_year",
        "place_of_death": "identity.place_of_birth",
        "relationship_to_applicant": "other.document_type",
        "document_number": "other.document_number",
        **DS160_EXTRACT_MAP,
    },
    "birth_certificate_child": {
        "child_full_name": "family.children_history",
        "full_name": "family.children_history",
        "child_date_of_birth": "family.children_history",
        "date_of_birth": "family.children_history",
        "child_place_of_birth": "family.children_history",
        "place_of_birth": "family.children_history",
        "child_gender": "family.children_history",
        "gender": "family.children_history",
        "father_name": "family.children_history",
        "mother_name": "family.children_history",
        "registration_number": "family.children_history",
        "children_used": "family.children_used",
        "children_count": "family.children_count",
        "children_history": "family.children_history",
        **DS160_EXTRACT_MAP,
    },
    "military_discharge": {
        "full_name": "identity.full_name",
        "name": "identity.full_name",
        "military_country": "additional.military_country",
        "military_branch": "additional.military_branch",
        "military_rank": "additional.military_rank",
        "military_specialty": "additional.military_specialty",
        "service_from_date": "additional.military_service_from",
        "service_to_date": "additional.military_service_to",
        "military_service_from": "additional.military_service_from",
        "military_service_to": "additional.military_service_to",
        "military_served_used": "additional.military_served_used",
        "document_number": "other.document_number",
        **DS160_EXTRACT_MAP,
    },
    "employment_letter": {
        "employer_name": "employment.employer_name",
        "job_title": "employment.job_title",
        "salary": "employment.salary",
        "employment_start_date": "employment.start_date",
        "present_employer": "employment.present_employer",
        "primary_occupation": "employment.primary_occupation",
        **CONTACT_AND_SOCIAL_MAP,
        **DS160_EXTRACT_MAP,
    },
    "application_form": {
        "primary_occupation": "employment.primary_occupation",
        "occupation_other_specify": "employment.occupation_other_specify",
        "present_employer": "employment.present_employer",
        "employer_name": "employment.employer_name",
        "employer_address": "employment.employer_address_line1",
        "employer_address_line1": "employment.employer_address_line1",
        "employer_city": "employment.employer_city",
        "employer_state": "employment.employer_state",
        "employer_postal_code": "employment.employer_postal_code",
        "employer_country": "employment.employer_country",
        "job_title": "employment.job_title",
        "employment_start_date": "employment.start_date",
        "start_date": "employment.start_date",
        "other_occupation_used": "employment.other_occupation_used",
        "other_occupation_detail": "employment.other_occupation_detail",
        "prior_jobs_10_years_used": "employment.prior_jobs_10_years_used",
        "prior_jobs_history": "employment.prior_jobs_history",
        "middle_school_name": "education.middle_school_name",
        "middle_school_address": "education.middle_school_address",
        "middle_school_period": "education.middle_school_period",
        "high_school_name": "education.high_school_name",
        "high_school_address": "education.high_school_address",
        "high_school_period": "education.high_school_period",
        "college_name": "education.college_name",
        "college_address": "education.college_address",
        "college_major": "education.college_major",
        "college_period": "education.college_period",
        **DS160_EXTRACT_MAP,
    },
    "address_document": {
        **CONTACT_AND_SOCIAL_MAP,
        **DS160_EXTRACT_MAP,
        "full_name": "identity.full_name",
        "name": "identity.full_name",
    },
    "ds260_customer_form": {
        **CONTACT_AND_SOCIAL_MAP,
        **DS160_EXTRACT_MAP,
    },
    "financial": {
        **CONTACT_AND_SOCIAL_MAP,
    },
    "diploma_transcript": {
        "school_name": "education.school_name",
        "degree": "education.degree",
        "gpa": "education.gpa",
        "graduation_date": "education.graduation_date",
        **DS160_EXTRACT_MAP,
    },
    "other": {
        "full_name": "identity.full_name",
        "name": "identity.full_name",
        "surname": "identity.family_name",
        "family_name": "identity.family_name",
        "given_name": "identity.given_names",
        "given_names": "identity.given_names",
        "date_of_birth": "identity.date_of_birth",
        "dob": "identity.date_of_birth",
        "nationality": "identity.nationality",
        "father_name": "family.father_name",
        "mother_name": "family.mother_name",
        "husband_full_name": "family.spouse_name",
        "wife_full_name": "family.spouse_name",
        "spouse_name": "family.spouse_name",
        "defendant_name": "identity.full_name",
        "plaintiff_name": "family.spouse_name",
        "document_number": "other.document_number",
        "document_type": "other.document_type",
        **CONTACT_AND_SOCIAL_MAP,
        **OTHER_FORM_MAP,
        **DS160_EXTRACT_MAP,
    },
}

_BASE_PROFILE_SECTIONS: dict[str, list[str]] = {
    "identity": [
        "identity.family_name",
        "identity.middle_name",
        "identity.given_names",
        "identity.full_name",
        "identity.full_name_native",
        "identity.other_name_used",
        "identity.other_names",
        "identity.gender",
        "identity.marital_status",
        "identity.date_of_birth",
        "identity.birth_city",
        "identity.birth_state",
        "identity.birth_country",
        "identity.place_of_birth",
        "identity.nationality",
    ],
    "passport": [
        "passport.number",
        "passport.issue_date",
        "passport.expiry_date",
        "passport.issuing_country",
    ],
    "immigration": [
        "immigration.visa_type",
        "immigration.visa_number",
        "immigration.visa_issue_date",
        "immigration.visa_expiry_date",
        "immigration.sevis_id",
        "immigration.i94_number",
        "immigration.class_of_admission",
        "immigration.admit_until_date",
    ],
    "contact_address": [
        "contact.address_line1",
        "contact.city",
        "contact.state",
        "contact.postal_code",
        "contact.country",
        "contact.address_from_date",
        "contact.other_addresses_used",
        "contact.other_addresses_history",
    ],
    "contact_communication": [
        "contact.phone_primary",
        "contact.phone_secondary",
        "contact.phone_work",
        "contact.other_phones_used",
        "contact.other_phones_history",
        "contact.email",
        "contact.other_emails_used",
        "contact.other_emails_history",
    ],
    "social_media": [
        "social.platform",
        "social.identifier",
        "social.other_used",
        "social.other_history",
    ],
}

# DS-260 workflow: dữ liệu per-document (ApplicantDocRecord + ds260_mapping).
# Không dùng form DS-160 thủ công trên Review — mỗi giấy tờ đã có bảng riêng.
PROFILE_SECTIONS: dict[str, list[str]] = {}

# Vietnamese labels for review UI (DS-160 Section A aligned)
_FIELD_LABELS_BASE: dict[str, str] = {
    "identity.family_name": "Họ (Surname / Last)",
    "identity.middle_name": "Tên đệm (Middle)",
    "identity.given_names": "Tên (Given / First)",
    "identity.full_name": "Họ và tên đầy đủ",
    "identity.full_name_native": "Họ tên bản ngữ",
    "identity.other_name_used": "Tên khác? (Yes/No)",
    "identity.other_names": "Chi tiết tên khác",
    "identity.gender": "Giới tính (Nam/Nữ)",
    "identity.marital_status": "Tình trạng hôn nhân",
    "identity.date_of_birth": "Ngày sinh (dd/mm/yyyy)",
    "identity.birth_city": "Thành phố nơi sinh",
    "identity.birth_state": "Tỉnh/Bang nơi sinh",
    "identity.birth_country": "Quốc gia nơi sinh",
    "identity.place_of_birth": "Nơi sinh (gộp)",
    "identity.nationality": "Quốc tịch",
    "passport.number": "Số hộ chiếu",
    "passport.issuing_country": "Quốc gia cấp hộ chiếu",
    "passport.issue_date": "Ngày cấp hộ chiếu",
    "passport.expiry_date": "Ngày hết hạn hộ chiếu",
    "contact.address_line1": "Địa chỉ hiện tại (số nhà, đường)",
    "contact.city": "Thành phố",
    "contact.state": "Tỉnh / Bang",
    "contact.postal_code": "Mã bưu điện",
    "contact.country": "Quốc gia",
    "contact.address_from_date": "Ở địa chỉ này từ (dd/mm/yyyy)",
    "contact.other_addresses_used": "Đã ở chỗ khác từ 16 tuổi? (Yes/No)",
    "contact.other_addresses_history": "Chi tiết địa chỉ trước đây",
    "contact.phone_primary": "Điện thoại chính",
    "contact.phone_secondary": "Điện thoại phụ",
    "contact.phone_work": "Điện thoại nơi làm việc",
    "contact.other_phones_used": "SĐT khác trong 5 năm? (Yes/No)",
    "contact.other_phones_history": "Chi tiết SĐT khác (5 năm)",
    "contact.email": "Email chính",
    "contact.other_emails_used": "Email khác trong 5 năm? (Yes/No)",
    "contact.other_emails_history": "Chi tiết email khác (5 năm)",
    "social.platform": "Mạng XH — nền tảng & tên (vd: Facebook – Dang Hung)",
    "social.identifier": "Link / ID mạng xã hội",
    "social.other_used": "MXH khác trong 5 năm? (Yes/No)",
    "social.other_history": "Chi tiết MXH khác (5 năm)",
    "family.father_name": "Cha — Họ tên (gộp, OCR)",
    "family.mother_name": "Mẹ — Họ tên (gộp, OCR)",
    "family.spouse_name": "Vợ/chồng — Họ tên (gộp, OCR)",
    "employment.employer_name": "Tên công ty (OCR)",
    "employment.job_title": "Chức danh",
    "employment.salary": "Lương",
    "employment.start_date": "Ngày bắt đầu làm việc",
}

FIELD_LABELS_VI: dict[str, str] = {**_FIELD_LABELS_BASE, **DS160_FIELD_LABELS_VI}

FORM_MAPPINGS: dict[str, dict[str, str]] = {
    "ds160_worksheet": {
        "Surname": "identity.family_name",
        "Middle Name": "identity.middle_name",
        "Given Names": "identity.given_names",
        "Full Name": "identity.full_name",
        "Full Name Native": "identity.full_name_native",
        "Other Name Used": "identity.other_name_used",
        "Other Names": "identity.other_names",
        "Sex": "identity.gender",
        "Marital Status": "identity.marital_status",
        "Date of Birth": "identity.date_of_birth",
        "City of Birth": "identity.birth_city",
        "State of Birth": "identity.birth_state",
        "Country of Birth": "identity.birth_country",
        "Place of Birth": "identity.place_of_birth",
        "Nationality": "identity.nationality",
        "Passport Number": "passport.number",
        "Passport Issuing Country": "passport.issuing_country",
        "Passport Issue Date": "passport.issue_date",
        "Passport Expiry": "passport.expiry_date",
        "Current Address": "contact.address_line1",
        "Address City": "contact.city",
        "Address State": "contact.state",
        "Postal Code": "contact.postal_code",
        "Address Country": "contact.country",
        "Address From Date": "contact.address_from_date",
        "Other Addresses Since 16": "contact.other_addresses_used",
        "Prior Address History": "contact.other_addresses_history",
        "Primary Phone": "contact.phone_primary",
        "Secondary Phone": "contact.phone_secondary",
        "Work Phone": "contact.phone_work",
        "Other Phones 5 Years": "contact.other_phones_used",
        "Other Phones Detail": "contact.other_phones_history",
        "Email": "contact.email",
        "Other Emails 5 Years": "contact.other_emails_used",
        "Other Emails Detail": "contact.other_emails_history",
        "Social Media Platform": "social.platform",
        "Social Media Identifier": "social.identifier",
        "Other Social Media 5 Years": "social.other_used",
        "Other Social Media Detail": "social.other_history",
        "Phone": "contact.phone_primary",
        "SEVIS ID": "immigration.sevis_id",
        "School Name": "education.school_name",
        "Program": "education.program_name",
        **DS160_FORM_MAPPINGS,
    },
    "i539_worksheet": {
        "Family Name": "identity.family_name",
        "Given Names": "identity.given_names",
        "Date of Birth": "identity.date_of_birth",
        "I-94 Number": "immigration.i94_number",
        "Class of Admission": "immigration.class_of_admission",
        "Admit Until": "immigration.admit_until_date",
    },
}
